<!-- Generated by xAI Grok (model: gpt-5.4) during provisioning. Edit freely. -->
<script setup lang="ts">
const runtimeConfig = useRuntimeConfig()
const publicConfig = runtimeConfig.public
const appName = publicConfig.appName && publicConfig.appName.length > 0 ? publicConfig.appName : 'Been Sober For.com'
const pageTitle = `${appName} — Count the days. Share the progress.`
const pageDescription = 'A calm, supportive place to track sober time, mark meaningful milestones, and share progress with the people cheering you on.'

useSeo({
  title: pageTitle,
  description: pageDescription,
  ogImage: {
    title: pageTitle
  }
})

useWebPageSchema({
  name: pageTitle,
  description: pageDescription
})

const { data: landing } = await useAsyncData('landing-page', async () => ({
  stats: [
    { label: 'Private setup', value: 'Fast' },
    { label: 'Milestone sharing', value: 'Simple' },
    { label: 'Daily motivation', value: 'Built in' }
  ],
  features: [
    {
      icon: 'i-lucide-calendar-heart',
      title: 'Track your sober time',
      description: 'Start from the date that matters and keep a clear, encouraging view of your progress.'
    },
    {
      icon: 'i-lucide-image',
      title: 'Make it personal',
      description: 'Add a profile photo and create a page that feels human, warm, and easy to share.'
    },
    {
      icon: 'i-lucide-share-2',
      title: 'Share milestones',
      description: 'Send your page to friends, family, or supporters whenever you want to celebrate growth.'
    },
    {
      icon: 'i-lucide-rotate-ccw',
      title: 'Start again with grace',
      description: 'If life happens, reset your count and keep moving forward without losing sight of the journey.'
    }
  ],
  steps: [
    {
      icon: 'i-lucide-user-plus',
      title: 'Create your page',
      description: 'Set up your profile in minutes with the essentials that matter most.'
    },
    {
      icon: 'i-lucide-clock-3',
      title: 'Watch time build',
      description: 'See your sober streak grow day by day with a simple, uplifting presentation.'
    },
    {
      icon: 'i-lucide-heart-handshake',
      title: 'Let others support you',
      description: 'Share your progress with the people who want to celebrate each step with you.'
    }
  ]
}))

const navItems = [
  { label: 'Features', to: '#features', icon: 'i-lucide-sparkles' },
  { label: 'How it works', to: '#how-it-works', icon: 'i-lucide-list-checks' },
  { label: 'Start', to: '#start', icon: 'i-lucide-rocket' }
]
</script>

<template>
  <div class="min-h-screen text-neutral-900">
    <UContainer class="py-4 sm:py-6">
      <div class="flex items-center justify-between gap-4 rounded-2xl border border-neutral-200/80 bg-white/80 px-4 py-3 backdrop-blur sm:px-5">
        <div class="flex items-center gap-3">
          <div class="accent-gradient flex h-10 w-10 items-center justify-center rounded-xl text-white shadow-sm">
            <UIcon name="i-lucide-leaf" class="h-5 w-5" />
          </div>
          <div>
            <p class="text-sm font-semibold tracking-tight">{{ appName }}</p>
            <p class="text-xs text-neutral-500">Supportive sobriety tracking</p>
          </div>
        </div>

        <div class="hidden md:block">
          <UNavigationMenu :items="navItems" />
        </div>

        <UButton to="#start" color="primary" variant="solid" icon="i-lucide-arrow-right" trailing>
          Get started
        </UButton>
      </div>
    </UContainer>

    <UContainer class="pb-12 pt-4 sm:pb-20 sm:pt-8">
      <section class="hero-surface grid-pattern relative overflow-hidden rounded-3xl border border-primary-100 px-5 py-10 sm:px-8 sm:py-14 lg:px-12">
        <div class="grid gap-10 lg:grid-cols-[1.15fr_0.85fr] lg:items-center">
          <div>
            <UBadge color="primary" variant="subtle" class="mb-4">
              Gentle accountability, beautifully presented
            </UBadge>

            <h1 class="max-w-3xl text-4xl font-semibold tracking-tight text-neutral-900 sm:text-5xl lg:text-6xl">
              Count the days,
              <span class="text-primary-700">honor the effort</span>,
              and share the progress.
            </h1>

            <p class="mt-5 max-w-2xl text-base leading-7 text-neutral-600 sm:text-lg">
              {{ pageDescription }}
            </p>

            <div id="start" class="mt-8 flex flex-col gap-3 sm:flex-row">
              <UButton to="/register" color="primary" size="xl" icon="i-lucide-rocket" trailing>
                Create your page
              </UButton>
              <UButton to="#features" color="neutral" variant="soft" size="xl" icon="i-lucide-arrow-down">
                Explore features
              </UButton>
            </div>

            <div class="mt-8 grid grid-cols-1 gap-3 sm:grid-cols-3">
              <UCard
                v-for="stat in landing?.stats"
                :key="stat.label"
                class="feature-card border border-white/70 bg-white/85"
              >
                <div class="text-2xl font-semibold tracking-tight text-neutral-900">{{ stat.value }}</div>
                <div class="mt-1 text-sm text-neutral-500">{{ stat.label }}</div>
              </UCard>
            </div>
          </div>

          <div>
            <UCard class="feature-card overflow-hidden border border-primary-100 bg-white/90">
              <div class="rounded-2xl border border-primary-100 bg-primary-50/70 p-4">
                <div class="flex items-center justify-between gap-3">
                  <div class="flex items-center gap-3">
                    <div class="flex h-12 w-12 items-center justify-center rounded-full bg-primary-100 text-primary-700">
                      <UIcon name="i-lucide-award" class="h-6 w-6" />
                    </div>
                    <div>
                      <p class="text-sm text-neutral-500">Milestone preview</p>
                      <p class="text-lg font-semibold text-neutral-900">A page worth sharing</p>
                    </div>
                  </div>
                  <UBadge color="success" variant="subtle">Steady progress</UBadge>
                </div>

                <div class="mt-6 rounded-2xl bg-white p-5 shadow-sm ring-1 ring-neutral-200/70">
                  <div class="flex items-center gap-4">
                    <div class="flex h-16 w-16 items-center justify-center rounded-2xl bg-neutral-100 text-neutral-500">
                      <UIcon name="i-lucide-user-round" class="h-8 w-8" />
                    </div>
                    <div>
                      <p class="font-medium text-neutral-900">Your sober story</p>
                      <p class="text-sm text-neutral-500">Photo, date, and milestones in one simple profile</p>
                    </div>
                  </div>

                  <USeparator class="my-5" />

                  <div class="grid grid-cols-2 gap-3">
                    <div class="rounded-xl bg-neutral-50 p-4">
                      <p class="text-xs uppercase tracking-[0.18em] text-neutral-400">Counter</p>
                      <p class="mt-2 text-2xl font-semibold text-neutral-900">365+</p>
                      <p class="text-sm text-neutral-500">days celebrated</p>
                    </div>
                    <div class="rounded-xl bg-neutral-50 p-4">
                      <p class="text-xs uppercase tracking-[0.18em] text-neutral-400">Sharing</p>
                      <p class="mt-2 text-2xl font-semibold text-neutral-900">1 link</p>
                      <p class="text-sm text-neutral-500">for supporters</p>
                    </div>
                  </div>
                </div>
              </div>
            </UCard>
          </div>
        </div>
      </section>
    </UContainer>

    <UContainer class="pb-10 sm:pb-16">
      <section id="features" class="py-6 sm:py-10">
        <div class="mb-8 max-w-2xl">
          <UBadge color="secondary" variant="subtle" class="mb-3">Why it feels different</UBadge>
          <h2 class="text-3xl font-semibold tracking-tight text-neutral-900 sm:text-4xl">Simple tools for a meaningful journey</h2>
          <p class="mt-3 text-neutral-600">
            Designed to feel calm, encouraging, and easy to return to every day.
          </p>
        </div>

        <div class="grid gap-4 sm:grid-cols-2 xl:grid-cols-4">
          <UCard
            v-for="feature in landing?.features"
            :key="feature.title"
            class="feature-card h-full border border-neutral-200/80 bg-white"
          >
            <div class="flex h-12 w-12 items-center justify-center rounded-xl bg-primary-50 text-primary-700">
              <UIcon :name="feature.icon" class="h-6 w-6" />
            </div>
            <h3 class="mt-4 text-lg font-semibold text-neutral-900">{{ feature.title }}</h3>
            <p class="mt-2 text-sm leading-6 text-neutral-600">{{ feature.description }}</p>
          </UCard>
        </div>
      </section>
    </UContainer>

    <UContainer class="pb-10 sm:pb-16">
      <section id="how-it-works" class="rounded-3xl border border-neutral-200 bg-white px-5 py-8 sm:px-8 sm:py-10">
        <div class="mb-8 flex flex-col gap-3 sm:flex-row sm:items-end sm:justify-between">
          <div class="max-w-2xl">
            <UBadge color="info" variant="subtle" class="mb-3">How it works</UBadge>
            <h2 class="text-3xl font-semibold tracking-tight text-neutral-900">A clear path from day one</h2>
            <p class="mt-3 text-neutral-600">No clutter, no steep learning curve, just a focused experience built around progress.</p>
          </div>
          <UButton to="/register" color="neutral" variant="soft" icon="i-lucide-user-plus">
            Open your account
          </UButton>
        </div>

        <div class="grid gap-4 md:grid-cols-3">
          <UCard
            v-for="(step, index) in landing?.steps"
            :key="step.title"
            class="feature-card border border-neutral-200/80 bg-neutral-50/60"
          >
            <div class="mb-4 flex items-center justify-between">
              <div class="flex h-11 w-11 items-center justify-center rounded-xl bg-white text-primary-700 ring-1 ring-neutral-200">
                <UIcon :name="step.icon" class="h-5 w-5" />
              </div>
              <span class="text-sm font-medium text-neutral-400">0{{ index + 1 }}</span>
            </div>
            <h3 class="text-lg font-semibold text-neutral-900">{{ step.title }}</h3>
            <p class="mt-2 text-sm leading-6 text-neutral-600">{{ step.description }}</p>
          </UCard>
        </div>
      </section>
    </UContainer>

    <UContainer class="pb-16 sm:pb-24">
      <section class="overflow-hidden rounded-3xl border border-primary-100 bg-primary-50/70 px-5 py-10 text-center sm:px-8">
        <div class="mx-auto max-w-2xl">
          <UBadge color="primary" variant="subtle" class="mb-4">Ready when you are</UBadge>
          <h2 class="text-3xl font-semibold tracking-tight text-neutral-900 sm:text-4xl">Build a page that reflects your progress, not just a number.</h2>
          <p class="mt-4 text-neutral-600">
            Start your counter, personalize your profile, and share milestones with the people who matter most.
          </p>
          <div class="mt-8 flex flex-col justify-center gap-3 sm:flex-row">
            <UButton to="/register" color="primary" size="xl" icon="i-lucide-heart">
              Start your journey
            </UButton>
            <UButton to="#how-it-works" color="neutral" variant="outline" size="xl" icon="i-lucide-arrow-up-right">
              See how it works
            </UButton>
          </div>
        </div>
      </section>
    </UContainer>
  </div>
</template>
